let quizdata = {
  "title" : "Can you name the countries of Europe?",
  "timeInSecs" : 300,
  "columns" : 4,
  "columnwidths" : ["1", "4"],
  "questionsAnswers" : [
    ["1", "Albania"],
    ["2", "Andorra"],
    ["3", "Austria"],
    ["4", "Belarus"],
    ["5", "Belgium"],
    ["6", "Bosnia and Herzegovina/bosnia"],
    ["7", "Bulgaria"],
    ["8", "Croatia"],
    ["9", "Cyprus"],
    ["10", "Czechia"],
    ["11", "Denmark"],
    ["12", "Estonia"],
    ["13", "Finland"],
    ["14", "France"],
    ["15", "Germany"],
    ["16", "Greece"],
    ["17", "Hungary"],
    ["18", "Iceland"],
    ["19", "Ireland"],
    ["20", "Italy"],
    ["21", "Kosovo"],
    ["22", "Latvia"],
    ["23", "Liechtenstein"],
    ["24", "Lithuania"],
    ["25", "Luxembourg"],
    ["26", "Malta"],
    ["27", "Moldova"],
    ["28", "Monaco"],
    ["29", "Montenegro"],
    ["30", "Netherlands"],
    ["31", "North Macedonia/macedonia"],
    ["32", "Norway"],
    ["33", "Poland"],
    ["34", "Portugal"],
    ["35", "Romania"],
    ["36", "Russia"],
    ["37", "San Marino"],
    ["38", "Serbia"],
    ["39", "Slovakia"],
    ["40", "Slovenia"],
    ["41", "Spain"],
    ["42", "Sweden"],
    ["43", "Switzerland"],
    ["44", "Turkey"],
    ["45", "Ukraine"],
    ["46", "United Kingdom/uk"],
    ["47", "Vatican City/vatican"],
  ]
}
console.log("Quiz Data Loaded Successfully");
